### ISSUE TITLE
German audio generation ignoring umlaut

### ISSUE THREAD

**Issue by gbauck** [microsoft/glue#4]
@nonstoptimm when using glue for generating german audio, umlaute (äöü) are ignored and left out in the generated audio. I used a textset formatted as utf-8 and de-DE-KatjaNeural as voice.

**Comment by nonstoptimm** [comment]
hi @gbauck , thanks for bringing it up - under investigation!

**Comment by nonstoptimm** [comment]
Hi Gregor, thanks again for bringing this up. The reason for this issue is a mix of an API and SDK change. Back then, it also worked with ä, ö... in the text, but not it is apparently no longer supported. I temporarily fixed this by introducing a normalization function. However, an upgrade to the newest SDK version is necessary, which I will tackle within the next 14 days. Cheers, Timm
